name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PLUGIN_ID: plugin-com-collinsdictionary
      REPO_USER_NAME: dicthub-plugin-publish
      REPO_USER_EMAIL: 47938489+dicthub-plugin-publish@users.noreply.github.com
      REPO_NAME: dicthub/DictHubPluginArtifacts
      REPO_BRANCH: master
      REPO_PATH: ./publish-repo

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Checkout plugin repository
      shell: bash
      run: |
        remote_repo="https://${REPO_USER_NAME}:${REPO_PUBLISH_TOKEN}@github.com/${REPO_NAME}.git"
        git clone ${remote_repo} -b ${REPO_BRANCH} ${REPO_PATH}
    - name: Copy built plugin to repository
      working-directory: ${{ env.REPO_PATH }}
      shell: bash
      run: |
        cp ../build/classes/kotlin/main/${PLUGIN_ID}.js plugins/${PLUGIN_ID}.js
        git add plugins/${PLUGIN_ID}.js
        git diff --cached
    - name: Commit plugin content
      working-directory: ${{ env.REPO_PATH }}
      shell: bash
      run: |
        git config --local user.email "${REPO_USER_EMAIL}"
        git config --local user.name "${REPO_USER_NAME}"
        git commit -m "Update ${PLUGIN_ID} to ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
    - name: Push changes
      working-directory: ${{ env.REPO_PATH }}
      env:
        REPO_PUBLISH_TOKEN: ${{ secrets.REPO_PUBLISH_TOKEN }}
      shell: bash
      run: |
        remote_repo="https://${REPO_USER_NAME}:${REPO_PUBLISH_TOKEN}@github.com/${REPO_NAME}.git"
        git push "${remote_repo}" HEAD:${REPO_BRANCH}
